<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
        <AzureFunctionsVersion>v4</AzureFunctionsVersion>
        <OutputType>Exe</OutputType>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="10.0.9" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.24.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.5.4" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
        <PackageReference Include="Microsoft.Extensions.Azure" Version="1.14.0" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.0" />
        <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="3.1.2" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.51.0" />
        <PackageReference Include="NServiceBus" Version="10.2.7" />
        <PackageReference Include="NServiceBus.AzureFunctions.Worker.ServiceBus" Version="7.1.1" />
        <PackageReference Include="NServiceBus.Extensions.Hosting" Version="4.1.0" />
        <PackageReference Include="NServiceBus.Newtonsoft.Json" Version="5.0.1" />
        <PackageReference Include="RestEase" Version="1.6.4" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="RestEase.HttpClientFactory" Version="1.6.4" />
        <PackageReference Include="SFA.DAS.CommitmentsV2.Messages" Version="3.88.5" />
        <PackageReference Include="SFA.DAS.Configuration.AzureTableStorage" Version="3.0.84" />
        <PackageReference Include="SFA.DAS.EmployerAccounts.Messages" Version="1.6.3195" />
        <PackageReference Include="SFA.DAS.Encoding" Version="1.1.76" />
        <PackageReference Include="SFA.DAS.Http" Version="3.2.69" />
        <PackageReference Include="SFA.DAS.LevyTransferMatching.Messages" Version="0.1.121-prerelease-7" />
        <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
        <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.9" />     
		<PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.23.0" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\SFA.DAS.LevyTransferMatching.Infrastructure\SFA.DAS.LevyTransferMatching.Infrastructure.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
</Project>
